### ISSUE TITLE
search index for falcon-refinedweb

### ISSUE THREAD

**Issue by WilliamsToTo** [allenai/wimbd#12]
Do you plan to build a search index for the [falcon-refinedweb dataset](https://huggingface.co/datasets/tiiuae/falcon-refinedweb)? This pre-trained dataset supports the falcon series LLMs, which are notable for their open access to both the model and dataset. Creating a search index could enhance our understanding of LLMs.

**Comment by yanaiela** [comment]
Sorry I missed that.
Probably not.
