### ISSUE TITLE
Index for Dolma v1.7

### ISSUE THREAD

**Issue by WilliamsToTo** [allenai/wimbd#15]
I noticed Dolma v1.7 is released. I previously retrieved texts on Dolma V1.5. Do we have the index for Dolma v1.7. Thanks.

**Comment by yanaiela** [comment]
Hey,

We do plan to add it, but I'm not sure exactly when it will be ready.
I'll update here once we do.

**Comment by yanaiela** [comment]
We added Dolma v1.7, and you can request access to the index [here](https://docs.google.com/forms/d/e/1FAIpQLScG8FgSCHl7nb4vFJnfHE5y5Pt0ObwA8gv2GMs6JYNbhAznPQ/viewform).
