### ISSUE TITLE
Unable to run several function

### ISSUE THREAD

**Issue by aflah02** [allenai/wimbd#16]
Hi
I am running the following script - 

```
from wimbd.es import es_init
from wimbd.es import count_documents_containing_phrases

es_dolma = es_init('es_config_dolma_1.yml')
es_others = es_init('es_config_7.yml')

from wimbd.es import get_indices

# This returns all indices, along with their total document counts.
print(get_indices())

# This also returns elasticsearch mapping information.
print(get_indices(return_mapping=True))

# Count the number of documents containing the term "legal".
print(count_documents_containing_phrases("docs_v1.5_2023-11-02", "legal", es = es_dolma))  # single term
```

I am facing the following issues - 

- The first and second prints just don't work and I get errors. I tried passing `es=es_dolma` as an arg since I saw it in the implementation but I still get this error - 

```
elasticsearch.AuthorizationException: AuthorizationException(403, 'security_exception', 'action [cluster:monitor/state] is unauthorized for API key id [{KEY}] of user [{USER_ID}], this action is granted by the cluster privileges [read_ccr,transport_client,cross_cluster_replication,manage_ccr,monitor,manage,all]')
```

- For the last print when I got access to the `.yml` files, one of them corresponded to Dolma while the other one was for the rest. I am not sure what all constitute the rest and when I switch `es_dolma` to `es_others` in the last print it breaks. I get the following error - 

```
elasticsearch.AuthorizationException: AuthorizationException(403, 'security_exception', 'action [indices:data/read/search] is unauthorized for API key id [{KEY}] of user [{USER_ID}] on indices [docs_v1.5_2023-11-02], this action is granted by the index privileges [read,all]')
```

I am probably doing something wrong but I can't figure out what

**Comment by yanaiela** [comment]
Hey,

As mentioned [here](https://github.com/allenai/wimbd/tree/main/wimbd/es#find-out-which-indices-exist-with-other-information-about-the-index), the `get_indices` function doesn't work with the given access key, but you can find the relevant indices names in the same page.

Re the `count_documents_containing_phrases` function, this is strange, as this should work.
Can you send me an email, and I'll send you a new key, perhaps the previous one I sent is no longer active.

**Comment by aflah02** [comment]
Gotcha! Thanks for sharing this
I'll also drop a mail
