### ISSUE TITLE
Demo Code

### ISSUE THREAD

**Issue by davzoku** [allenai/wimbd#3]
Hi wimbd team, great work in open sourcing this much needed tool. Can I check if the frontend code for the demo is available?

Thank you.

Walter

**Comment by yanaiela** [comment]
Hey,

It turns out to be more complicated than initially expected.
I'm still working on it, and will keep you updated.

**Comment by yanaiela** [comment]
Here it is:
https://github.com/allenai/wimbd-demo-public
